# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 12:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('mobile_number', models.IntegerField(max_length=10)),
                ('personal_email_id', models.EmailField(max_length=254)),
                ('marital_status', models.BooleanField()),
                ('marriage_anniv', models.DateField()),
                ('citizen', models.CharField(max_length=15)),
                ('religion', models.CharField(max_length=15)),
                ('blood_group', models.CharField(max_length=4)),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
