# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abchrms', '0004_auto_20180621_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='marriage_anniv',
            field=models.DateField(blank=True, null=True),
        ),
    ]
