# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-04 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abchrms', '0007_auto_20180625_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(choices=[(b'A+', b'A+'), (b'B+', b'B+'), (b'AB+', b'AB+'), (b'A-', b'A-'), (b'B-', b'B-'), (b'AB-', b'AB-')], max_length=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.BooleanField(choices=[(b'True', b'Married'), (b'False', b'Unmarried')]),
        ),
        migrations.AlterField(
            model_name='employment',
            name='confirmation_status',
            field=models.CharField(choices=[(b'Confirmed', b'Confirmed'), (b'Probation', b'Probation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employment',
            name='emp_type',
            field=models.CharField(choices=[(b'Full-time', b'Full-time'), (b'Contractual', b'Contractual')], max_length=20),
        ),
    ]
