# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abchrms', '0007_auto_20180625_1609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactons',
            new_name='Transactions',
        ),
        migrations.AlterField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.BooleanField(choices=[('True', 'Married'), ('False', 'Unmarried')]),
        ),
        migrations.AlterField(
            model_name='employment',
            name='confirmation_status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Probation', 'Probation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employment',
            name='emp_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Contractual', 'Contractual')], max_length=20),
        ),
    ]
