# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abchrms', '0009_transactions_tran_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('PL', 'Privelege Leave'), ('CL', 'Casual Leave'), ('SL', 'Sick Leave')], max_length=2),
        ),
    ]
