# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 06:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abchrms', '0010_auto_20180703_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('PL', 'Privelege Leave'), ('CL', 'Casual Leave'), ('SL', 'Sick Leave')], max_length=2)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('no_of_days', models.IntegerField()),
                ('leave_reason', models.CharField(choices=[('Personal', 'Personal'), ('Vacation', 'Vacation'), ('Marriage', 'Marriage'), ('Sick Leave', 'Sick Leave'), ('Family', 'Family'), ('Others', 'Others')], max_length=20)),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abchrms.Employee')),
            ],
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_availed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_carryforward',
            field=models.IntegerField(default=0),
        ),
    ]
