# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abchrms', '0011_auto_20180704_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_txn_type', models.CharField(choices=[('add', 'add'), ('remove', 'remove')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='dependents',
            name='dep_rel',
            field=models.CharField(choices=[('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('father', 'Father'), ('mother', 'Mother')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='tran_type',
            field=models.CharField(choices=[('leave', 'leave'), ('dependent', 'dependent')], max_length=20),
        ),
        migrations.AddField(
            model_name='dependenttransaction',
            name='dep_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abchrms.Dependents'),
        ),
        migrations.AddField(
            model_name='dependenttransaction',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abchrms.Employee'),
        ),
    ]
