# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-05 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abchrms', '0008_auto_20180704_1452'),
        ('abchrms', '0011_auto_20180704_1207'),
    ]

    operations = [
    ]
