# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abchrms', '0012_merge_20180705_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_txn_type', models.CharField(choices=[('add', 'add'), ('remove', 'remove'), ('edit', 'edit')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('TI', 'Travel Insurance'), ('ULIP', 'Child Plan'), ('EQMF', 'Equity MF SIP'), ('LI', 'Term Life Insurance')], max_length=10)),
                ('product_name', models.CharField(max_length=50)),
                ('product_disp_text', models.TextField()),
                ('product_cat', models.CharField(choices=[('P', 'Protecting'), ('I', 'Investing'), ('F', 'Financing'), ('A', 'Advising')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RuleEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('txn_type', models.CharField(choices=[('leave', 'leave'), ('dependent', 'dependent')], max_length=20)),
                ('rules', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='dependents',
            name='dep_rel',
            field=models.CharField(choices=[('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('father', 'Father'), ('mother', 'Mother')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='employment',
            name='confirmation_status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Probation', 'Probation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employment',
            name='emp_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Contractual', 'Contractual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='tran_type',
            field=models.CharField(choices=[('leave', 'leave'), ('dependent', 'dependent')], max_length=20),
        ),
        migrations.AddField(
            model_name='dependenttransaction',
            name='dep_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abchrms.Dependents'),
        ),
        migrations.AddField(
            model_name='dependenttransaction',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abchrms.Employee'),
        ),
    ]
