# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abchrms', '0012_auto_20180705_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('TI', 'Travel Insurance'), ('ULIP', 'Child Plan'), ('EQMF', 'Equity MF SIP'), ('LI', 'Term Life Insurance')], max_length=10)),
                ('product_name', models.CharField(max_length=50)),
                ('product_disp_text', models.TextField()),
                ('product_cat', models.CharField(choices=[('P', 'Protecting'), ('I', 'Investing'), ('F', 'Financing'), ('A', 'Advising')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RuleEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('txn_type', models.CharField(choices=[('leave', 'leave'), ('dependent', 'dependent')], max_length=20)),
                ('rules', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='dependenttransaction',
            name='dep_txn_type',
            field=models.CharField(choices=[('add', 'add'), ('remove', 'remove'), ('edit', 'edit')], max_length=10),
        ),
    ]
