# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abchrms', '0013_auto_20180706_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependenttransaction',
            name='dep_id',
        ),
        migrations.RemoveField(
            model_name='dependenttransaction',
            name='emp_id',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='RuleEngine',
        ),
        migrations.AlterField(
            model_name='dependents',
            name='dep_rel',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='tran_type',
            field=models.CharField(default='undefined', max_length=20),
        ),
        migrations.DeleteModel(
            name='DependentTransaction',
        ),
    ]
