# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abchrms', '0015_auto_20180706_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetransaction',
            name='leave_type',
            field=models.CharField(choices=[('PL', 'Privilege Leave'), ('CL', 'Casual Leave'), ('SL', 'Sick Leave')], max_length=2),
        ),
    ]
